#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/asmvik/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# copied and modified from https://medium.com/@khhini/yabai-a-tilling-window-manager-for-macos-03822421250c

# Disable specific apps
excluded_apps="System Settings
Finder
Slack
Discord
Activity Monitor
MacPass
IINA
QuickTime Player
zoom.us
Preview
Archive Utility
LaTeXiT
Cisco Secure Client
Microsoft Outlook
Minecraft Launcher
java"

echo "$excluded_apps" | while IFS= read -r app; do
  yabai -m rule --add app="^${app}$" manage=off
done
yabai -m rule --apply

yabai -m config layout bsp
yabai -m config window_placement second_child

# Padding
yabai -m config external_bar all:40:0
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config right_padding 8
yabai -m config left_padding 8
yabai -m config window_gap 8

# mouse settings
# yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action stack

echo "yabai configuration loaded.."
